### ISSUE TITLE
Search broken in the app

### ISSUE THREAD

**Issue by kaczorws** [nmoya/hltb-mobile-app#25]
Hello, it seems that recently (started about mid-May) search inside the app stopped working. You can type anything but the results will:
- always show default values consistent with what is shown on the HLTB website before you start typing (see screenshots below)
- will not show any images

This is what is now shown inside the app after you search for anything:
<img src="https://user-images.githubusercontent.com/18362307/170132688-42b03efe-3d42-416f-95dc-b62b3adf2d16.jpg" width="300">

This is what HLTB website is showing when you only click on search but before you start typing:
<img src="https://user-images.githubusercontent.com/18362307/170131986-9b24df25-cca7-47e4-81f2-760c472e834c.png" width="600">

As you can see, it seems that search value is ignored and just default values are shown. However, images are not working anymore. Probably something changed on the HLTB site code and is not handled by the app.

**Comment by nmoya** [comment]
Thank you for reporting. Just released an app update that should fix the issue!

**Comment by kaczorws** [comment]
Thanks, working flawlessly now. Great app by the way, I use it all the time quickly access HLTB and plan my games ahead :)
