### ISSUE TITLE
Request failed with status code 404

### ISSUE THREAD

**Issue by rombat** [nmoya/hltb-mobile-app#29]
Hi there,
It seems that the app is broken, I've got a 404 error every time I search for games (that are really present in HLTB).
Here I searched for [Lunar](https://howlongtobeat.com/?q=Lunar)
![Screenshot_20220917-083740_How Long To Beat](https://user-images.githubusercontent.com/9024503/190845589-aef69041-2c9c-49ea-b16c-8afb1f609c52.jpg)

**Comment by rombat** [comment]
Ok actually its `howlongtobeat` module that should be fixed:
https://github.com/ckatzorke/howlongtobeat/issues/40

**Comment by nmoya** [comment]
Hey, I'm retiring the project (I don't have an Android phone anymore).

My recommendation is for you to use the HLTB mobile version from your phone browser.
