### ISSUE TITLE
Search appears to be broken in the app

### ISSUE THREAD

**Issue by kaczorws** [nmoya/hltb-mobile-app#35]
Hello, it seems that search inside the app stopped working again (last time it was in 2022).
Searching for anything returns this error:

<img src="https://github.com/user-attachments/assets/8d4a8ad7-9194-4c99-a928-5d56d8e64ef3" width="400">

I've read on Steam Deck Gaming (https://x.com/SteamDeckGaming/status/1819394270257664322) that HLTB removed it's API although can't see any confirmation on official HTLB forums, but maybe it's connected to this?

**UPDATE:**
Found some open issue on GitHub of HLTB Api regarding this:
https://github.com/ScrappyCocco/HowLongToBeat-PythonAPI/issues/25

**Comment by rombat** [comment]
Same here

**Comment by nmoya** [comment]
Hey, I'm retiring the project (I don't have an Android phone anymore).

My recommendation is for you to use the HLTB mobile version from your phone browser.
